version: '2.1'

services:
  api_gateway:
    image: api_gateway
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000



version: "2"

services:
  api-gateway:
    image: localhost:5000/api-gateway:latest
    ports:
      - "80"
    links:
      - redis
    networks:
      - front-tier
      - back-tier

  db:
    image: postgres:9.5
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: